dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat AGG_DAY_WISE_7am_7pm.sql
use etldb;
CREATE TABLE IF NOT EXISTS AGG_DAY_WISE_7am_7pm(
CALL_ORIGINATING_NUMBER STRING
,CALL_START_DATE DATE
,CELL_ID STRING
,NO_OF_EVENTS INT
);
INSERT INTO AGG_DAY_WISE_7am_7pm
SELECT CALL_ORIGINATING_NUMBER,CALL_START_DATE,CELL_ID,count(CALL_ORIGINATING_NUMBER) from mno_7am_7pm group by CALL_ORIGINATING_NUMBER,CALL_START_DATE,CELL_ID ;
dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat AGG_DAY_WISE_TIME_7am_7pm.sql
use etldb;
CREATE TABLE IF NOT EXISTS AGG_DAY_WISE_TIME_7am_7pm(
CALL_ORIGINATING_NUMBER STRING
,CALL_START_DATE DATE
,CALL_START_TIME TIMESTAMP
,CELL_ID STRING
);
INSERT INTO AGG_DAY_WISE_TIME_7am_7pm
SELECT CALL_ORIGINATING_NUMBER,CALL_START_DATE,max(CALL_START_TIME),CELL_ID from mno_7am_7pm group by CALL_ORIGINATING_NUMBER,CALL_START_DATE,CELL_ID ;
dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat AGG_MONTH_WISE_7am_7pm.sql
use etldb;
CREATE TABLE IF NOT EXISTS AGG_MONTH_WISE_7am_7pm(
CALL_ORIGINATING_NUMBER STRING
,CALL_MONTH_YEAR STRING
,CELL_ID STRING
,NO_OF_EVENTS INT
);
INSERT INTO AGG_MONTH_WISE_7am_7pm
SELECT CALL_ORIGINATING_NUMBER,CONCAT(MONTH(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(CALL_START_DATE, 'yyyy-MM-dd')))),'-',YEAR(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(CALL_START_DATE, 'yyyy-MM-dd'))))) as concated,CELL_ID,count(CALL_ORIGINATING_NUMBER) from mno_7am_7pm group by CALL_ORIGINATING_NUMBER,CONCAT(MONTH(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(CALL_START_DATE, 'yyyy-MM-dd')))),'-',YEAR(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(CALL_START_DATE, 'yyyy-MM-dd'))))),CELL_ID;
dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat HOMELOCATION_DAY_7am_7pm.sql
use etldb;
CREATE TABLE IF NOT EXISTS HOMELOCATION_DAY_7am_7pm(
CALL_ORIGINATING_NUMBER STRING
,CALL_START_DATE DATE
,CALL_START_TIME TIMESTAMP
,CELL_ID STRING
,RANK INT
);

INSERT INTO HOMELOCATION_DAY_7am_7pm
SELECT RNK.CALL_ORIGINATING_NUMBER,RNK.CALL_START_DATE,RNK.CALL_START_TIME,RNK.CELL_ID,RNK  FROM
(SELECT CALL_ORIGINATING_NUMBER,CALL_START_DATE,CALL_START_TIME,CELL_ID ,RANK() OVER (PARTITION  BY CALL_ORIGINATING_NUMBER,CALL_START_DATE ORDER BY CALL_START_TIME DESC) AS RNK
FROM HOMELOCATION_DAY_STEP2_7am_7pm  GROUP BY CALL_ORIGINATING_NUMBER,CALL_START_DATE,CELL_ID,CALL_START_TIME ORDER BY CALL_START_DATE )RNK
WHERE RNK.RNK=1;
dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat HOMELOCATION_DAY_STEP1_7am_7pm.sql
use etldb;
CREATE TABLE IF NOT EXISTS HOMELOCATION_DAY_STEP1_7am_7pm(
CALL_ORIGINATING_NUMBER STRING
,CALL_START_DATE STRING
,HOME_LOCATION STRING
,RANK INT
);

INSERT INTO HOMELOCATION_DAY_STEP1_7am_7pm
SELECT RNK.CALL_ORIGINATING_NUMBER,RNK.CALL_START_DATE,RNK.CELL_ID,RNK  FROM
(SELECT CALL_ORIGINATING_NUMBER,CALL_START_DATE,CELL_ID, NO_OF_EVENTS,RANK() OVER (PARTITION  BY CALL_ORIGINATING_NUMBER,CALL_START_DATE ORDER BY NO_OF_EVENTS DESC) AS RNK
FROM AGG_DAY_WISE_7am_7pm  GROUP BY CALL_ORIGINATING_NUMBER,CALL_START_DATE,CELL_ID,NO_OF_EVENTS ORDER BY CALL_START_DATE )RNK
WHERE RNK.RNK=1;
dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat HOMELOCATION_DAY_STEP2_7am_7pm.sql

use etldb;
CREATE TABLE IF NOT EXISTS HOMELOCATION_DAY_STEP2_7am_7pm(
CALL_ORIGINATING_NUMBER STRING
,CALL_START_DATE DATE
,CALL_START_TIME TIMESTAMP
,CELL_ID STRING
,RANK INT
);

INSERT INTO HOMELOCATION_DAY_STEP2_7am_7pm
SELECT B.CALL_ORIGINATING_NUMBER,B.CALL_START_DATE,A.CALL_START_TIME,B.HOME_LOCATION,B.RANK FROM  AGG_DAY_WISE_TIME_7am_7pm A JOIN HOMELOCATION_DAY_STEP1_7am_7pm B
ON A.CALL_ORIGINATING_NUMBER=B.CALL_ORIGINATING_NUMBER AND A.CELL_ID=B.HOME_LOCATION AND A.CALL_START_DATE=B.CALL_START_DATE ;
dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat MNO_DAILY_AGG_7am_7pm.sql
use etldb;
create table if not exists MNO_DAILY_AGG_7am_7pm(
CELL_ID STRING
,CALL_START_DATE STRING
,NO_OF_EVENTS INT
,NO_OF_UNIQUE_ID INT
);
insert INTO  MNO_DAILY_AGG_7am_7pm
select a.cell_id,a.call_start_date,a.no_of_events,b.no_of_unique_id from MNO_DAILY_AGG_cdr_7am_7pm a join MNO_DAILY_AGG_home_7am_7pm b where a.cell_id=b.cell_id and a.call_start_date=b.call_start_date ;
dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat MNO_DAILY_AGG_cdr_7am_7pm.sql
use etldb;
CREATE TABLE IF NOT EXISTS MNO_DAILY_AGG_cdr_7am_7pm(
CELL_ID STRING
,CALL_START_DATE STRING
,NO_OF_EVENTS INT
);
INSERT INTO MNO_DAILY_AGG_cdr_7am_7pm
SELECT CELL_ID,CALL_START_DATE,count(CALL_ORIGINATING_NUMBER) from mno_7am_7pm group by CELL_ID,CALL_START_DATE;
dialssh@hn0-dialma:~/dev/agg_on_7am_7pm$ cat MNO_DAILY_AGG_home_7am_7pm.sql
use etldb;
CREATE TABLE IF NOT EXISTS MNO_DAILY_AGG_home_7am_7pm(
CELL_ID STRING
,CALL_START_DATE STRING
,NO_OF_UNIQUE_ID INT
);
INSERT INTO MNO_DAILY_AGG_home_7am_7pm
SELECT CELL_ID,CALL_START_DATE,count(distinct(CALL_ORIGINATING_NUMBER)) from HOMELOCATION_DAY_7am_7pm group by CELL_ID,CALL_START_DATE;
