use etldb;
CREATE  TABLE IF NOT EXISTS mno_data_comp(
USAGE_TYPE_NAME STRING
,CALL_ORIGINATING_NUMBER STRING
,CALL_TERMINATING_NUMBER STRING
,CALL_START_DATE STRING
,CALL_START_TIME STRING
,Duration String
,LAC_ID STRING
,CELL_ID STRING)
COMMENT 'full data'
STORED AS ORC;

INSERT OVERWRITE TABLE mno_data_comp SELECT * FROM mno_data;
